replicaCount: 1

image:
  # 저장소의 위치는 harbor 를 바라 보도록 한다 
  #repository: 172.16.8.40/library/greet
  #image  저장소의 위치는 ECR 를 바라 보도록 한다 
  repository: 473479139700.dkr.ecr.ap-northeast-2.amazonaws.com/greet
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 # FastAPI 포트